name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: |
        dotnet publish -o publish/ -r win-x64 -c Release --self-contained /p:PublishSingleFile=true
        mv './publish/GIDOCS.exe' ./publish/GameInventory.exe
        
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GameInventory.exe
        path: publish/GameInventory.exe
    
    #- name: Create Release
     # id: create_release
      #uses: actions/create-release@v1
      #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #with:
        #tag_name: ${{ github.ref }}
        #release_name: Release ${{ github.ref }}
